### ISSUE TITLE
support client protocol to "love" a track.

### ISSUE THREAD

**Issue by carnager** [hrkfdn/mpdas#13]
mpd has this nifty feature, where other clients can request actions from other clients. The "love" flag is a perfect example, where this can be useful.
http://www.musicpd.org/doc/protocol/client_to_client.html

the love flag is documented here:
http://www.last.fm/api/show/track.love

**Comment by carnager** [comment]
btw, client protocol would also be useful to e.g. pause/unpause scrobbling.without killing the program

**Comment by hrkfdn** [comment]
I have just committed this functionality (loving for now), but only briefly tested it. Could you guys see if it works for you?

The channel is "mpdas", so 'mpc sendmessage mpdas love' should love the currently playing track.

**Comment by carnager** [comment]
new version segfaults for me...

Program received signal SIGABRT, Aborted.
0x00007ffff70baa97 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff70baa97 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff70bbe6a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff70fa2b3 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff70ff72e in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff70ffeeb in _int_free () from /usr/lib/libc.so.6
#5  0x00007ffff7bcb5e6 in mpd_connection_free () from /usr/lib/libmpdclient.so.2
#6  0x0000000000406b06 in CMPD::Connect() ()
#7  0x0000000000406d40 in CMPD::CMPD() ()
#8  0x00000000004038d3 in main ()

**Comment by hrkfdn** [comment]
Hey,

can you try again with the latest commit? If that does not work, can you build it with debug infos by adding "-g" to CXXFLAGS and LDFLAGS and send me another backtrace?

**Comment by carnager** [comment]
ok, now i cant get authentication to work... tried with both real password and md5sum of the same... 
(19:26:40) [ERROR] Code: 4
(19:26:40) [ERROR] Authentication failed. Please check your login data.

**Comment by hrkfdn** [comment]
The authentication process hasn't been touched. Are you sure your MD5sum is correct? If you've used "echo pass | md5sum" make sure you pass -n to echo, so that the newline is not included in the hash.

**Comment by carnager** [comment]
no clue what went wrong. maybe lastfm was acting on me. tried again today and it worked. including loving of a track!

**Comment by hrkfdn** [comment]
Glad it works! Thanks for your feedback :)

**Comment by carnager** [comment]
hmm and suddenly it doesnt work anymore. it says "loved track successfully" but nothing happens. *sigh*

**Comment by hrkfdn** [comment]
just tried this myself and it worked fine, are you still affected? is your clock set up correctly?
