### ISSUE TITLE
Repeated play only scribbled once

### ISSUE THREAD

**Issue by yshui** [hrkfdn/mpdas#20]

**Comment by timss** [comment]
See #16. Might be last.fm cleaning up what they believe to be duplicates on their side.

**Comment by yshui** [comment]
@timss I checked the log, and repeated plays are only submitted once

**Comment by hrkfdn** [comment]
Hey. For clarification: Do you mean repeated as in using MPDs repeat mode or manually playing the track again?

**Comment by yshui** [comment]
MPD repeat mode

**Comment by ibrokemypie** [comment]
bump

**Comment by hrkfdn** [comment]
@ibrokemypie It's on my radar, just a little busy these days.
