### ISSUE TITLE
Scrobbled tracks not saving

### ISSUE THREAD

**Issue by Firestorrrm** [hrkfdn/mpdas#30]
Mpdas scrobbles the current song, but as soon as the song changes it doesn't save on Last.FM. Is there a fix for this?

**Comment by pcwalden** [comment]
This is a known problem with the cache file getting corrupt.

I documented this problem in Issue #10 

My cure was:

"Solved I think.

Looks like the .mpdascache file was corrupt. In the above sample, the first entry was bad and kept failing. The rest of the cache was never subsequently processed. I deleted the .mpdascache and mpdas is working now."

This continues to happen occasionally and so I have a cron job that checks for and removes bad cache files daily.

**Comment by Firestorrrm** [comment]
I never had the file so I created it. However, every time I launched mpdas, the file would disappear. If I entered something in the file, it would say "Scrobbled successfully."

**Comment by hrkfdn** [comment]
I'll need some debug logs of the problem occurring, otherwise it's very hard to track down the source of it.

Which version are you upgrading from? What is your mpd version?

As for the cache file corrupting: I'll have a closer look, esp. at the file provided by @pcwalden. Nevertheless, as I said, the mechanism will be reworked soon using a more mature data format.

**Comment by Firestorrrm** [comment]
Where would I find these logs?

0.3.1 was installed from
`brew install mpdas`

**Comment by hrkfdn** [comment]
As of mpdas >=0.4 libmpdclient is used. Please make sure you're using the latest mpd and libmpdclient version.

Also you have reported the exact same bug for a different scrobbler: https://github.com/mopidy/mopidy-scrobbler/issues/20 

Maybe the problem lies somewhere else?

**Comment by Firestorrrm** [comment]
`Warning: libmpdclient-2.10 already installed`

```
Error in connection() 61 - Connection refused
(22:43:59) [INFO] Connected to MPD.
(22:44:01) [INFO] Last.fm handshake successful. SessionID: <snip>
(22:44:01) [INFO] New song: The Weeknd - Acquainted
(22:44:02) [INFO] Updated "Now Playing" status successfully.
(22:44:02) [INFO] Scrobbling:  -
(22:44:02) [INFO] Scrobbled successfully.
(22:45:51) [INFO] New song: Kanye West;Lupe Fiasco - Touch The Sky
(22:45:51) [INFO] Updated "Now Playing" status successfully.
```

**Comment by hrkfdn** [comment]
Thanks. That does look similar to the issue @pcwalden had. I'll have a look at the caching again, soon.

**Comment by hrkfdn** [comment]
I'm going to close this for now. Please let me know if it reoccurs. Preferably with a debug log and cache file (if existent).
