### ISSUE TITLE
Not autostarting with systemd

### ISSUE THREAD

**Issue by grawlinson** [hrkfdn/mpdas#35]
Hello,

How exactly do you get mpdas to autostart upon system startup?

I've enabled the mpdas service, but it shows this on startup:

```shell
$ systemctl --user status mpdas
● mpdas.service - AudoScrobbler client for MPD
   Loaded: loaded (/usr/lib/systemd/user/mpdas.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

```

And I end up having to start the service.

EDIT: More information.

I use Arch Linux and I'm using the user service instead of a global service.

**Comment by hrkfdn** [comment]
Hey,

I do not provide any .service files, so I can't help you there. If 'manual' startup works, it should work as a user service, too. Something must be wrong with your configuration or service file.
