### ISSUE TITLE
libre.fm: Code 6

### ISSUE THREAD

**Issue by privong** [hrkfdn/mpdas#43]
I have encountered an error after upgrading to version 0.4.3. I am using mpdas to connect to libre.fm and am now getting the following error:

```
$ mpdas
(11:49:39) [ERROR] You are not root. Not changing user ..
(11:49:39) [INFO] Using Libre.fm service URL
(11:49:39) [INFO] Connected to MPD.
(11:49:41) [ERROR] Code: 6
(11:49:41) [INFO] Closing mpdas.
```

I get the same error whether I use the MD5 password or have it entered into the config file as plaintext. I was unable to find additional information in the mpdas source on what Code 6 means. 

My configuration file is:

```
username = librefmusername
password = mypassword
runas = myuser
debug = 1
service = librefm
```

Please let me know if there is additional information I can provide.

**Comment by hrkfdn** [comment]
I had to make some changes to the protocol implementation as Last.fm is deprecating parts that we used for authentication. Seems that Libre.fm doesn't like this. I'll have to create an account and investigate this.

**Comment by hrkfdn** [comment]
Libre.fm does not implement the latest Last.fm API, which is why with the new changes it doesn't work anymore: https://github.com/foocorp/gnu-fm/blob/master/nixtape/2.0/index.php#L803

Seems it's on their list, but hasn't been fixed yet. Not sure what to do here, I could implement two authentication mechanisms, but I rather wouldn't want to.

**Comment by privong** [comment]
> Seems it's on their list, but hasn't been fixed yet. Not sure what to do here, I could implement two authentication mechanisms, but I rather wouldn't want to.

Understandable. Since opening the issue, I've downgraded to the last version that supports the old auth mechanism. I'll avoid upgrading for now. I guess I'll play it by ear.

Maybe for now you could have `mpdas` throw an error if `service = libre.fm`, so other users will know it's an issue with the authorization method?

**Comment by hrkfdn** [comment]
I guess, but then I'd have to push out another release at some point to re-enable it. A warning could do, I suppose. Their last commit was in October 2016, guess they're not that active anymore? Just wondering, as we can't be the only ones noticing this..

**Comment by privong** [comment]
Re: their development activity, I don't really know if it's a temporary lull or if it's been abandoned. But I was also a little surprised no one else has reported the issue.

**Comment by hrkfdn** [comment]
@privong I have re-implemented the changes required by Libre.fm. Could you give the master branch a try?

**Comment by privong** [comment]
@hrkfdn Sorry it took me so long to check this. I had a long period of not using mpd and just resumed using it again. I can confirm that your fix worked and I can again use mpdas with libre.fm. Thanks for fixing this!

**Comment by motorto** [comment]
Sorry to reopen an old issue , @hrkfdn 

But I am having the same issue:

```
 $> mpdas -c $HOME/.mpdasrc
(20:53:47) [INFO] Using Libre.fm service URL
(20:53:47) [INFO] Connected to MPD.
(20:53:48) [ERROR] Code: 6
(20:53:48) [INFO] Closing mpdas.
```

This is my config on $HOME/.mpdasrc

```
service = librefm
username = username
password = password
host = localhost
debug = 1
```
