### ISSUE TITLE
Error code 13

### ISSUE THREAD

**Issue by onodera-punpun** [hrkfdn/mpdas#46]
Since the new password commit (so since a month+ ago) I get the following erro when launching mpdas:

```
(15:51:57) [ERROR] Code: 13
(15:51:57) [ERROR] Invalid method signature.
```

My config:

```
#
# /etc/mpdas.conf: mpdas configuration
#

# Last.fm username and password
username = onodera-punpun
password = password

# The user mpdas runs as
user "mpd"

# End of file
```

I launch mpdas using `-c /etc/mdpas.conf`. Oh and I also use libressl, that might have something to do with it.

**Comment by hrkfdn** [comment]
This is during authentication/handshake or scrobbling?

I'm on OpenBSD, so it's probably not LibreSSL.

**Comment by hrkfdn** [comment]
Can you see if the latest commit fixes it?

**Comment by onodera-punpun** [comment]
This fixed it, thanks a lot :).

Could you please tag a new release soon :)

**Comment by hrkfdn** [comment]
Done ;)
