### ISSUE TITLE
Unable to compile mpdas on OSMC

### ISSUE THREAD

**Issue by massdosage** [hrkfdn/mpdas#47]
I'm trying to set up mpdas on OSMC on a Raspberry Pi to scrobble songs from MPD installed locally. I've downloaded the 0.4.4 source code and tried to run "make" on it. After installing various missing libraries it's now failing compilation with the following error:

> osmc@osmc:~/temp/mpdas-0.4.4$ make
> g++ `pkg-config --cflags libmpdclient libcurl` -DCONFDIR="\"/usr/local/etc\"" -DVERSION="\"0.4.4\"" -c -o main.o main.cpp
> g++ `pkg-config --cflags libmpdclient libcurl` -DCONFDIR="\"/usr/local/etc\"" -DVERSION="\"0.4.4\"" -c -o md5.o md5.cpp
> g++ `pkg-config --cflags libmpdclient libcurl` -DCONFDIR="\"/usr/local/etc\"" -DVERSION="\"0.4.4\"" -c -o utils.o utils.cpp
> g++ `pkg-config --cflags libmpdclient libcurl` -DCONFDIR="\"/usr/local/etc\"" -DVERSION="\"0.4.4\"" -c -o mpd.o mpd.cpp
> g++ `pkg-config --cflags libmpdclient libcurl` -DCONFDIR="\"/usr/local/etc\"" -DVERSION="\"0.4.4\"" -c -o audioscrobbler.o audioscrobbler.cpp
> g++ `pkg-config --cflags libmpdclient libcurl` -DCONFDIR="\"/usr/local/etc\"" -DVERSION="\"0.4.4\"" -c -o cache.o cache.cpp
> g++ `pkg-config --cflags libmpdclient libcurl` -DCONFDIR="\"/usr/local/etc\"" -DVERSION="\"0.4.4\"" -c -o config.o config.cpp
> config.cpp: In function ‘int IniHandler(void*, const char*, const char*, const char*)’:
> config.cpp:11:33: error: ‘std::string’ has no member named ‘front’
>      if(val.length() >= 2 && val.front() == '\"' && val.back() == '\"') {
>                                  ^
> config.cpp:11:56: error: ‘std::string’ has no member named ‘back’
>      if(val.length() >= 2 && val.front() == '\"' && val.back() == '\"') {
>                                                         ^
> Makefile:19: recipe for target 'config.o' failed

Any ideas? Hopefully I'm missing something simple.

**Comment by hrkfdn** [comment]
Try the master branch. It has one more commit (compared to the latest release), which makes the codebase more compatible with older compilers.

**Comment by massdosage** [comment]
Yeah, master works, thanks. Was just suggesting maybe doing a 0.4.5 release with this, but not too bothered as I'm fine working against master for now.
