### ISSUE TITLE
Scrobble works on 'Artist' and not on 'Album Artist'?

### ISSUE THREAD

**Issue by clasick** [hrkfdn/mpdas#48]
I've noticed that this plugin scrobbles each track with the artist and not the album artist, so the scrobbles don't end up adding up to total plays of artist.

for example - 
Feather by Nujabes scrobbles to artist Nujabes feat. Cise Star & AKIN instead of just Nujabes, thus Nujabes ends up having no plays throughout an entire album as there are so many features... 

I searched around for a one liner in the settings to solve this problem but it doesn't seem to a option.... kinda seems like a no brainer to scrobble using Album Artist.

**Comment by hrkfdn** [comment]
Yeah, I guess I could scrobble the album artist, if it is set. Sound reasonable?

**Comment by pcwalden** [comment]
In my experience the situation is inverted, usually album artist is something like "Various" or "Various Artists". The artist tag is typically the artist for the track. Maybe some logic is needed to test album artist for "contains Various" before using it.

**Comment by hrkfdn** [comment]
This makes things a little more problematic as files are not usually tagged in a consistent manner :( I know that Last.fm does some auto-correction of input and probably has way smarter mechanisms. I'm unsure how to proceed here.

**Comment by clasick** [comment]
Maybe a way to just include an option in the config file? We could have the best of both worlds.

**Comment by hrkfdn** [comment]
That's an idea. I'll do some testing first. Maybe it is sufficient to just submit both, artist and album artist, and let Last.fm choose the most appropriate.

**Comment by hrkfdn** [comment]
I am now also scrobbling the album artist. It's been pushed to the master branch, could you guys check if it works and see if it improves the artist detection?

**Comment by hrkfdn** [comment]
Whoops, must have disabled the issues feature accidentally.

**Comment by clasick** [comment]
@hrkfdn Just got around to testing it, the artist scrobbled appears to be the same before... :/

**Comment by clasick** [comment]
I think it would help to see how Clementine handles this issue. In the scrobbling section, Clementine has a feature called 'Scrobble using Album Artist tag when available' which works rather beautifully.

**Comment by SuperBFG7** [comment]
I believe using album artist vs. artist depends on whether the album is a compilation (i.e. album artist is Various Artists or similar) or not. Beets for example has a flag for that. I'm not sure however if it is saved in the tags and available in mpd and mpd clients.

Am 30. Okt. 2017, 19:17 +0100 schrieb Vignesh Kumar <notifications@github.com>:

**Comment by hrkfdn** [comment]
It looks like Clementine just sends the album artist instead of the artist,
if the option and tag are set. No further checking if it is "Various
artists" or something similar. I'll look into implementing that. Thanks for
testing! :)

**Comment by massdosage** [comment]
You should always try submit as much info when scrobbling as possible, so if you have an album and a track artist you should send both based on the values set in the track metadata. You should leave them "as is" and not do anything additional with "artists" like "Various Artists". Last.fm should be able to work things out correctly on their end. I used to work there and co-wrote the backend of the scrobbling API so I at least know how things _used_ to be :) So I think what you've done here with passing on whatever value was set for "Album Artist" if present in the metadata is correct.

**Comment by hrkfdn** [comment]
@massdosage That's good to know, thanks for chiming in. I'll leave it the way it is now, then, and close the issue.
